---
title: "Seoul Bike Sharing Demand"
author: "STAT 420, Summer 2022, Scott Downey, Sushma Ponna, William Shih"
output:
  html_document: 
    theme: readable
    toc: yes
urlcolor: cyan
---

***

## Introduction
Rental bikes and bike sharing are important in urban cities as bikes reduce traffic congestion, reduce air pollution, and improve last mile transportation. Bikes will become even more important in the future as cities urbanize and have high population densities. The goal of this project is to build a model that will accurately predict the volume of bike rentals at a given time. Predicting exactly many bikes to provide makes sure that there will be no shortage of bikes that would result in people waiting for a bike yet also not have a large surplus of bikes as that would be a waste of resources.

The data set contains bike sharing data in Seoul from 12/1/2017 to 11/30/2018. Each observation represents an hour of time. The variable of interest for prediction is the rented bike count for the hour. The 12 variables that will be considered as predictors include the hour of day, temperature, humidity, wind speed, visibility, dew point, solar radiation, rainfall, snowfall, season of year, holiday (boolean), and functioning (boolean). The dataset is associated with two papers published in a journal in February and March 2020 related to gradient tree boosting, but here we'll be only using linear regression. and is found at the Seoul government website http://data.seoul.go.kr/

A further description of the dataset can be found at https://archive.ics.uci.edu/ml/datasets/Seoul+Bike+Sharing+Demand

## Methods

```{r, message = FALSE, warning = FALSE}
#Load the bike sharing data into R
require(dplyr)
library(tidyr)
colnames = c("Date","RentedBikeCount","Hour","Temperature","Humidity","Wind","Visibility",
             "DewPoint","SolarRadiation","Rainfall","Snowfall","Season","Holiday","Functional")
data = read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00560/SeoulBikeData.csv",
                col.names = colnames)
data = tibble(data)

#Separate 'Date'  into Day, Month and Year
data = separate(data, "Date", c("Day", "Month", "Year"))

#Convert predictors to factors or integers as needed
data$Season = as.factor(data$Season)
data$Holiday = as.factor(data$Holiday)
data$Functional = as.factor(data$Functional)

data$Day = as.integer(data$Day)
data$Month = as.integer(data$Month)
data$Year = as.integer(data$Year)

#Remove 'Year' as this won't be a good predictor for future years
data = subset(data, select = c("Day","Month","RentedBikeCount","Hour","Temperature",
                               "Humidity","Wind","Visibility","DewPoint","SolarRadiation",
                               "Rainfall","Snowfall","Season","Holiday","Functional"))


#Temporary to use for understanding data/analysis
#str(data)
#View(data)
plot(RentedBikeCount ~ ., data = data, col = "dodgerblue")

#Split data into training and test data
set.seed(42)
trn_size = as.integer(0.7 * count(data))
trn_idx = sample(nrow(data), trn_size)
bike_trn = data[trn_idx, ]
bike_tst = data[-trn_idx, ]

#Model building and selection
model_full_add = lm(RentedBikeCount ~ ., data = bike_trn)
summary(model_full_add)

n = length(resid(model_full_add))
aic_model = step(model_full_add, direction = "backward")
bic_model = step(model_full_add, span = RentedBikeCount ~ 1, direction = "backward", k = log(n))

anova(aic_model, model_full_add)
anova(bic_model, model_full_add)

```

## Results

## Discussion

## Appendix

